---
kind: pipeline
type: docker
name: default

steps:
  - name: build_poetry
    image: python
    volumes:
      - name: cache_poetry
        path: /root/.cache/pypoetry
      - name: poetry_bin
        path: /root/.poetry/
    commands:
      - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - /root/.poetry/bin/poetry install

  - name: check_formatting
    image: python
    volumes:
      - name: cache_poetry
        path: /root/.cache/pypoetry
      - name: poetry_bin
        path: /root/.poetry/
    commands:
      - /root/.poetry/bin/poetry run black --check pywirelessmbus tests

  - name: check_linting
    image: python
    volumes:
      - name: cache_poetry
        path: /root/.cache/pypoetry
      - name: poetry_bin
        path: /root/.poetry/
    commands:
      - /root/.poetry/bin/poetry run flake8 pywirelessmbus tests

  - name: tests
    image: python
    volumes:
      - name: cache_poetry
        path: /root/.cache/pypoetry
      - name: poetry_bin
        path: /root/.poetry/
    commands:
      - /root/.poetry/bin/poetry run pytest -x

  - name: make release
    image: python
    volumes:
      - name: cache_poetry
        path: /root/.cache/pypoetry
      - name: poetry_bin
        path: /root/.poetry/
    environment:
      GH_TOKEN:
        from_secret: GITHUB_TOKEN
      PYPI_TOKEN:
        from_secret: PYPI_TOKEN
    commands:
      - mkdir dist
      - /root/.poetry/bin/poetry run semantic-release publish
    when:
      branch:
        include:
          - master

trigger:
  event:
    exclude:
      - tag
      - pull_request

volumes:
  - name: cache_poetry
    host:
      path: /tmp/drone/cache/pypoetry

  - name: poetry_bin
    host:
      path: /tmp/drone/cache/poetry_bin
